### ISSUE TITLE
Dimension error with fraction in exponent

### ISSUE THREAD

**Issue by gitanjali1990** [schymans/environmental-science-for-sagemath#74] opened 2019-05-16 19:12 UTC
from essm import Eq, solve
from essm.equations import Equation
from essm.variables import Variable
from essm.equations.leaf.energy_water import eq_Rll
from essm.variables.leaf.energy_water import R_ll, a_sh, epsilon_l, T_l, T_w
from essm.variables.physics.thermodynamics import sigm

class eq_Tl_Rll(Equation):
    """T_l as function of R_ll"""
    expr = Eq(T_l, soln[3])   
print(eq_Tl_Rll)
    
class eq_Tl_Rll1(Equation):
    """T_l as function of R_ll"""
    expr = Eq(T_l, (R_ll/(a_sh*epsilon_l*sigm) + T_w**4)**(1/4))

**Comment by schymans** [comment] 2019-05-16 21:18
Thanks for reporting. Here is the above example in its complete form:
```python
from essm import Eq, solve
from essm.equations import Equation
from essm.variables import Variable
from essm.equations.leaf.energy_water import eq_Rll
from essm.variables.leaf.energy_water import R_ll, a_sh, epsilon_l, T_l, T_w
from essm.variables.physics.thermodynamics import sigm

soln = solve(eq_Rll, T_l)

class eq_Tl_Rll(Equation):
    """T_l as function of R_ll"""
    expr = Eq(T_l, soln[1])
print(eq_Tl_Rll)

class eq_Tl_Rll1(Equation):
    """T_l as function of R_ll"""
    expr = Eq(T_l, (R_ll/(a_sh*epsilon_l*sigm) + T_w**4)**(1/4))
```
returns on the current master:

```
Eq(T_l, (R_ll/(a_sh*epsilon_l*sigm) + T_w**4)**(1/4))

---------------------------------------------------------------------------
ValueError  
(...)
ValueError: Dimension of "T_l" is Dimension(temperature), but it should be the same as (R_ll/(a_sh*epsilon_l*sigm) + T_w**4)**0.25, i.e. Dimension(temperature**1.0)
```

**Comment by schymans** [comment] 2019-05-16 22:31
OK, the problem is that `1/4` in the exponent gets evaluated to 0.25 when entering the equation by hand, whereas using `soln` retains the `1/4`:
```python
print(soln[1])
print((R_ll/(a_sh*epsilon_l*sigm) + T_w**4)**(1/4))
```
returns
```
(R_ll/(a_sh*epsilon_l*sigm) + T_w**4)**(1/4)
(R_ll/(a_sh*epsilon_l*sigm) + T_w**4)**0.25
```
This is actually a common problem, described here: https://docs.sympy.org/latest/gotchas.html#evaluating-expressions-with-floats-and-rationals
"If you include numbers in a SymPy expression, they will be sympified automatically, but there is one gotcha you should be aware of. If you do <number>/<number> inside of a SymPy expression, Python will evaluate the two numbers before SymPy has a chance to get to them. The solution is to sympify() one of the numbers, or use Rational."

So in the example of the OP, one of the following would work:
```python
from essm import Eq, solve
from essm.equations import Equation
from essm.variables import Variable
from essm.equations.leaf.energy_water import eq_Rll
from essm.variables.leaf.energy_water import R_ll, a_sh, epsilon_l, T_l, T_w
from essm.variables.physics.thermodynamics import sigm
from sympy import S, Rational

class eq_Tl_Rll1(Equation):
    """T_l as function of R_ll"""
    expr = Eq(T_l, (R_ll/(a_sh*epsilon_l*sigm) + T_w**4)**(S(1)/4))
print(eq_Tl_Rll1)

class eq_Tl_Rll2(Equation):
    """T_l as function of R_ll"""
    expr = Eq(T_l, (R_ll/(a_sh*epsilon_l*sigm) + T_w**4)**Rational(1,4))
print(eq_Tl_Rll2)
```

**Comment by schymans** [comment] 2019-07-16 08:08
I am closing this issue, as the solution is to avoid non-symbolic fractions in equations, as shown above.

**Closed as completed by schymans** 2019-07-16 08:08 UTC
